### ISSUE TITLE
Requesting new build

### ISSUE THREAD

**Issue by PierreLeGuen** [ReClassNET/ReClass.NET#100]
Hello, 
It has been more than 500 commits and 1 year since you didn't published a build.
I'm struggling to build from source, I'm 100% on Linux and .NET apps are quiet frustrating to build.
Thanks in advance,

**Comment by stevemk14ebr** [comment]
https://github.com/ReClassNET/ReClass.NET/issues/47

**Comment by PierreLeGuen** [comment]
When using msbuild and gcc with mono > 5 : 

```bash
Extensions/XAttributeExtensions.cs(10,18): error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater. [/home/pierre/Documents/git/ReClass.NET/ReClass.NET/ReClass.NET.csproj]
Done Building Project "/home/pierre/Documents/git/ReClass.NET/ReClass.NET/ReClass.NET.csproj" (default targets) -- FAILED.

Build FAILED.

"/home/pierre/Documents/git/ReClass.NET/ReClass.NET/ReClass.NET.csproj" (default target) (1) ->
(CoreCompile target) -> 
  Extensions/XAttributeExtensions.cs(10,18): error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater. [/home/pierre/Documents/git/ReClass.NET/ReClass.NET/ReClass.NET.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.52
```

When changing langVersion in csproj to 7.3 it still doesn't build.

**Comment by KN4CK3R** [comment]
What error do you get with C# 7.3?

**Comment by PierreLeGuen** [comment]
After changing from `<LangVersion>lastest</LangVersion>` to  `<LangVersion>7.3</LangVersion>`.
I get the same error
```bash
Extensions/XAttributeExtensions.cs(10,18): 
error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater. 
[/home/pierre/Documents/git/ReClass.NET/ReClass.NET/ReClass.NET.csproj]

Done Building Project "/home/pierre/Documents/git/ReClass.NET/ReClass.NET/ReClass.NET.csproj" (default targets) --
 FAILED.
```

Btw I tested on two laptops and it happens every time. Thanks for your time.

**Comment by KN4CK3R** [comment]
`<LangVersion>lastest</LangVersion>` is the latest version available (7.3). As you see in the error message C# 7.0 is used. Maybe Mono doesn't support newer versions?

**Comment by stevemk14ebr** [comment]
As an aside, it sounds like time for some continuous integration tooling to be added to the repo

**Comment by PierreLeGuen** [comment]
@KN4CK3R Mono does support C# 7.3 since mid 2018 (mono 5.0.0):

![image](https://user-images.githubusercontent.com/26087574/54665793-4b6fd880-4ae8-11e9-9f08-daa482af6608.png)

Maybe it's still missing some features?

@stevemk14ebr I think you right, it could be done pretty easily with Travis CI as an app on github.

**Comment by KN4CK3R** [comment]
Disclaimer: I have no Mono knowlegde.
`csc` is the Mono compiler for .NET Core. But ReClass.NET isn't a .NET Core project (yet (I'm waiting for the .NET Core 3 release with WinForms support #73)). The makefile uses the `msbuild` compiler which may not support C# 7.3 (https://github.com/mono/mono/issues/6854). To be able to build again, you need to revert this commit efdf372. Maybe I will stick to C# 7.0 until the project is converted to .NET Core.

**Comment by PierreLeGuen** [comment]
After reversing to efdf372. The error is even bigger.
I've no idea why it happens... Maybe not supported yet ?
```bash
UI/EnumComboBox.cs(11,60): error CS8107: Feature 'enum generic type constraints' is not available in C# 7.0. Please use language version 7.3 or greater. [/home/pierre/Documents/git/ReClass.NET-efdf3729f7c74256b9be0888515711a6f39da514/ReClass.NET/ReClass.NET.csproj]
Memory/RemoteProcess.cs(209,58): error CS8107: Feature 'unmanaged generic type constraints' is not available in C# 7.0. Please use language version 7.3 or greater. [/home/pierre/Documents/git/ReClass.NET-efdf3729f7c74256b9be0888515711a6f39da514/ReClass.NET/ReClass.NET.csproj]
Memory/RemoteProcess.cs(572,71): error CS8107: Feature 'unmanaged generic type constraints' is not available in C# 7.0. Please use language version 7.3 or greater. [/home/pierre/Documents/git/ReClass.NET-efdf3729f7c74256b9be0888515711a6f39da514/ReClass.NET/ReClass.NET.csproj]
Memory/MemoryBuffer.cs(160,51): error CS8107: Feature 'unmanaged generic type constraints' is not available in C# 7.0. Please use language version 7.3 or greater. [/home/pierre/Documents/git/ReClass.NET-efdf3729f7c74256b9be0888515711a6f39da514/ReClass.NET/ReClass.NET.csproj]
Memory/MemoryBuffer.cs(167,48): error CS8107: Feature 'unmanaged generic type constraints' is not available in C# 7.0. Please use language version 7.3 or greater. [/home/pierre/Documents/git/ReClass.NET-efdf3729f7c74256b9be0888515711a6f39da514/ReClass.NET/ReClass.NET.csproj]
UI/EnumDescriptionDisplay.cs(11,59): error CS8107: Feature 'enum generic type constraints' is not available in C# 7.0. Please use language version 7.3 or greater. [/home/pierre/Documents/git/ReClass.NET-efdf3729f7c74256b9be0888515711a6f39da514/ReClass.NET/ReClass.NET.csproj]
Done Building Project "/home/pierre/Documents/git/ReClass.NET-efdf3729f7c74256b9be0888515711a6f39da514/ReClass.NET/ReClass.NET.csproj" (default targets) -- FAILED.

Build FAILED.
```
MSBuild version
```
> msbuild -V                                                                                                                               
Microsoft (R) Build Engine version 16.0.0.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by PierreLeGuen** [comment]
I just tried the commit 779cb2e and it compiles.
Hoping .NET Core 3 release with WinForms soon

**Comment by KN4CK3R** [comment]
You shouldn't reverse to efdf372 but undo the changes that were made in this commit. After you have done this you can use the lastest source (minus this commit).

**Comment by KittoniuM** [comment]
to compile reclass a few months ago i had to download stuff and remove something from some package manager or somethin

**Comment by joaoescribano** [comment]
To be true, I've tried a lot.. and a lot to compile it.. it simply doesn't compile at any circumstances under mono in ubuntu 18.04.

I already have mono 5+, nuget (installed by apt, also .exe through mono nuget.exe) to install dependencies (like SQLite) and nothing, absolutely nothing makes it compile...

It would be awesome if a new release been published.

Note:
Also, the old release doesn't run under mono.

**Comment by KN4CK3R** [comment]
After fixing 3162e04 I was able to compile the project with Mono 5.20 without problems. Try it out!

**Comment by KN4CK3R** [comment]
I released ReClass.NET 1.2 for you.

**Comment by joaoescribano** [comment]
Thanks so much, i'll try as soon i get home :)

Thanks

**Comment by joaoescribano** [comment]
I could not stand to wait... haha

![image](https://user-images.githubusercontent.com/1336613/56164208-93c6cd00-5fa6-11e9-976d-4c1ff4658f6c.png)


Seems working, I'll try to use as soon I get home.. o just had to see it working!
