### ISSUE TITLE
Plugin not showing

### ISSUE THREAD

**Issue by johmarjac** [ReClassNET/ReClass.NET#104]
Hi,

I am currently trying to write my own plugin for accessing memory using a driver and receive/send the data via sockets.

However, the plugin when I copy it does not get shown up. I debugged ReClass.NET and found [that code](https://github.com/ReClassNET/ReClass.NET/blob/master/ReClass.NET/Plugins/PluginManager.cs#L72) very strange.

When I changed that line to:
```if (checkProductName && (fvi.ProductName == PluginInfo.PluginName) || (fvi.ProductName == PluginInfo.PluginNativeName))```

It started to work obviously. Whats the thought behind this behaviour that it has currently? Is it intended or is it a bug?

**Comment by KN4CK3R** [comment]
I don't understand the problem. You have to include the Plugin "Magic Number" like shown in https://github.com/ReClassNET/ReClass.NET-SamplePlugin/blob/master/Managed/Properties/AssemblyInfo.cs#L12 or https://github.com/ReClassNET/ReClass.NET-SamplePlugin/blob/master/Native/SamplePluginNative.rc#L73

**Comment by johmarjac** [comment]
Oh I see now how it works. Thanks

**Comment by KN4CK3R** [comment]
Not your fault, there is no documentation currently beside the public plugin source codes.

**Comment by johmarjac** [comment]
@KN4CK3R I just didn't look into AssemblyInfo.cs as in only rare cases the settings there matter xD

I dont know Source of ReClass.NET yet, so yeah it is just a lack of documentation. But I figured now. Thanks for the hint :)

**Comment by ItsJokerZz** [comment]
Got the latest source and plugin sample, built the managed one, added the dll to `x64/plugins/` and it doesnt show up.

<img width="2560" height="1392" alt="Image" src="https://github.com/user-attachments/assets/838a3cd6-6d9c-47db-ad84-beb1f499a1c0" />

So I removed the capital from the plugins directory and now it works, but is defined with a capital.
```csharp
		public const string PluginsFolder = "Plugins";
```
