### ISSUE TITLE
How do I add elements to an array?

### ISSUE THREAD

**Issue by ross-weir** [ReClassNET/ReClass.NET#105]
Excuse any ignorance but I can't for the life of me figure out how to add elements to an array.

For example I have an array of `byte`s with 10 elements, how do I add the extra 9:

![](https://i.imgur.com/pIEuo7R.png)

I'm unable to right click the line:

```
0000 0040000C UInt8 = 0 0x0 //
```

Which is how I would have expected to add bytes to the array.

Thanks for the awesome project. Are there any channels (IRC/Discord/etc) that I could have visited to ask this question instead of opening an issue?

**Comment by KN4CK3R** [comment]
Double click the [1] after the name lets you edit the element count.

**Comment by ross-weir** [comment]
🤦‍♂ 

Thanks.

**Comment by KN4CK3R** [comment]
I need to add some documentation! #106
