### ISSUE TITLE
Bitfield is hard to read.

### ISSUE THREAD

**Issue by gir489** [ReClassNET/ReClass.NET#107]
![image](https://user-images.githubusercontent.com/7742541/57252540-5a6c0500-701a-11e9-8027-5e981aa197f8.png)

When trying to read the bitfield, it seems the bit numbers desync the further up the field you go. 16 is actually on field 15. At least according to my windows calculator when I put the DWORD value in to it.

![image](https://user-images.githubusercontent.com/7742541/57252594-825b6880-701a-11e9-9d18-e27f1d815025.png)

**Comment by KN4CK3R** [comment]
Your ReClass screenshot doesn't show 0x88000 in the bitfield.
![grafik](https://user-images.githubusercontent.com/1666336/57253007-f3684380-704d-11e9-800f-de45e6ec18fb.png)
It looks ok to me. Bit 16 and 20 are set. Maybe I should add a space after 4 bits too.

**Comment by gir489** [comment]
I think the issue is you consider the least significant bit "bit 1", whereas most bitfields consider them bit 0. 0. Example: https://en.wikipedia.org/wiki/Bit_field#Processor_status_register

In programming it's just general common practice to start at 0. So because of this, what you consider bit 16 is actually bit 15. This is also done for power of 2 reasons. "Bit 16" is the same as 1 << 16.

**Comment by KN4CK3R** [comment]
I have implemented groups for the bitstring now.
![grafik](https://user-images.githubusercontent.com/1666336/57465175-5b04d580-727e-11e9-89b5-1b24fa92e4cc.png)

**Comment by gir489** [comment]
That makes it even easier to read, just like the Windows calculator.
