### ISSUE TITLE
Class Pointer removed?

### ISSUE THREAD

**Issue by LiquidObsidian** [ReClassNET/ReClass.NET#112]
Why was class pointer removed? The only button still there is class instance, it's pretty annoying having to set the pointer type to class instance everytime.

**Comment by KN4CK3R** [comment]
Because there is no need for a specific ClassPointer node if there is a pointer which can wrap all other types.

If you compile ReClass.NET you can add
```csharp
public override void Initialize()
{
	var node = new ClassInstanceNode();
	node.Initialize();

	ChangeInnerNode(node);
}
```
to the PointerNode class to restore the old feel. Currently I don't know if I should add this method.

**Comment by OutsideTheBoxGit** [comment]
I also liked the old way.

**Comment by LiquidObsidian** [comment]
I think you should leave the PTR button there and just add the old CLS PTR button back, it was just a handy shortcut and I see no reason to remove it.
