### ISSUE TITLE
Make module walk only use RPM

### ISSUE THREAD

**Issue by stevemk14ebr** [ReClassNET/ReClass.NET#131]
All this kind of stuff: https://github.com/ReClassNET/ReClass.NET/blob/master/NativeCore/Windows/EnumerateRemoteSectionsAndModules.cpp#L8

make it use RPM only. This way stuff like drivers can get away with implementing a single method. Applies to some other native classes i think too

**Comment by KN4CK3R** [comment]
You talk about reimplementing `VirtualQueryEx`, `CreateToolhelp32Snapshot`, ...?

**Comment by stevemk14ebr** [comment]
Correct, not total re-implementations obviously but enough to pull out the info reclass needs. CreateToolhelp is probably easier to pull out then virtualquery

**Comment by gir489** [comment]
Why? What’s the point of this?

**Comment by stevemk14ebr** [comment]
> This way stuff like drivers can get away with implementing a single method

**Comment by namazso** [comment]
https://github.com/reactos/reactos/blob/master/sdk/lib/epsapi/enum/modules.c#L30
this might help

**Comment by namazso** [comment]
check #135
