### ISSUE TITLE
Can't connect to Microsoft Visual Studio process (32-bit) and read RTTI info?

### ISSUE THREAD

**Issue by Karaulov** [ReClassNET/ReClass.NET#133]
Can't connect to Microsoft Visual Studio process (32-bit) and read RTTI info?

I don't see process in list. Tried run x86 and x64 ReClass...

**Comment by KN4CK3R** [comment]
Maybe you need to run ReClass as admin? For me it works just fine (without admin) 
![grafik](https://user-images.githubusercontent.com/1666336/63828140-d2fa2700-c965-11e9-8214-4d92bb4b3a05.png)

**Comment by Karaulov** [comment]
For example Game.dll from Warcraft III 1.26a

**Comment by GH-Rake** [comment]
That game has anticheat that prevents it.  Blizzard probably strips RTTI from their binaries anyways.

**Comment by Karaulov** [comment]
I run reclass without admin privileges, sorry))))

But i don't see any info from RTTI Game.dll

**Comment by Karaulov** [comment]
@KN4CK3R yes. Help how to work with RTTI ??? This tool can parse RTTI from file??? (MSVC RTTI)

**Comment by GH-Rake** [comment]
At runtime, put the address of a class object into reclass.  Look at the vTable pointer and you will see the RTTI info.  If you don't see it, then the RTTI is either stripped or it's not available for that class.

Here's what it looks like if it works:
https://youtu.be/wEkwCW4oJrY?t=181
