### ISSUE TITLE
Platform dependent integer (size_t)

### ISSUE THREAD

**Issue by fshauge** [ReClassNET/ReClass.NET#134]
I'm working on reversing a program which has a 64-bit and a 32-bit version. The two versions are essentially identical, just compiled for different targets. Having an integer node with the size dependent on the current platform would reduce the amount of work. The current workaround is to use a void pointer, but it does not show the correct purpose of the node. Code generation should also be able to generate a `size_t` rather than `void*`.

**Comment by KN4CK3R** [comment]
After moving to .NET 5 ReClass.NET can use this C# 9 feature: https://github.com/dotnet/csharplang/issues/435 for such a node without `IntPtr` / `UIntPtr` and casts.
