### ISSUE TITLE
Change Array Size

### ISSUE THREAD

**Issue by UnquestionablePresence** [ReClassNET/ReClass.NET#136]
![Capture](https://user-images.githubusercontent.com/30274499/65557834-47d76700-defa-11e9-96c1-b4654ea47a29.PNG)
I added an array, but the size is stuck to 4. I've tried searching everywhere around the GUI. The sideways arrows don't change anything, and the drop-down menu just lets me change the type.

**Comment by KN4CK3R** [comment]
Just make a double click on the `[1]` to edit the array length. The `Size=4` tells you the memory size in bytes.

**Comment by UnquestionablePresence** [comment]
Thanks for your response! Unrelated, but hopefully better support for 4k/Hidpi displays will be added in the future. Here is how it looks:

![image](https://user-images.githubusercontent.com/30274499/66248172-4a4f7300-e6e9-11e9-8be7-523250a2c687.png)

With Windows 10's Enhanced DPI mode, the text becomes blurry

![image](https://user-images.githubusercontent.com/30274499/66248160-1aa06b00-e6e9-11e9-8b30-988b6f5ec5d6.png)
