### ISSUE TITLE
112 commits since release.

### ISSUE THREAD

**Issue by gir489** [ReClassNET/ReClass.NET#141]
What is holding up v1.3?

**Comment by UnquestionablePresence** [comment]
I am wondering as well. The only thing that could take a long time is if he is converting it to WPF. Otherwise there isn't really any reason to be waiting so long for 1.3.

**Comment by stevemk14ebr** [comment]
Compile it and you can have it today!

**Comment by gir489** [comment]
There should be a github action to build this then if the owner doesn't want to have a release schedule.

**Comment by stevemk14ebr** [comment]
You are very demanding, and I find it rude

**Comment by gir489** [comment]
If being direct is wrong, then I don't want to be right. If you're offended by the fact of your own laziness, that sounds like a personal issue.

**Comment by Timboy67678** [comment]
this is github, not fosshub. fork it and link a CI like travis, appveyor. Only lazy one here is you

**Comment by UnquestionablePresence** [comment]
> 
> 
> this is github, not fosshub. fork it and link a CI like travis, appveyor. Only lazy one here is you

You're overreacting, he just made a suggestion that the developer should do that. Could only benefit everyone, doubt he was trying to be aggressive. Linking a CI for another person's project is weird.

**Comment by stevemk14ebr** [comment]
> If you're offended by the fact of your own laziness, that sounds like a personal issue.
it was completely justified. There's a difference between asking, and expecting then insulting when it's not done.

**Comment by appleman1232** [comment]
i mean why u guys even flaiming over version number? lol.

back on topic i also agree to release current repo as 1.3, since there are big improvements for sure.

**Comment by KittoniuM** [comment]
Gir489 is rite, and Ur wrong. evribodi need Latest ReclassNET.
Older reclass, dem pipo have wahala and dey no no how compile latest reclass.
I, compile reclass ~1 hour. Reclass wan chop and I, cant provide.

I beg Kn4cker, plz

**Comment by gir489** [comment]
Yeah because thinking of the user is such begging. Fuck me for thinking this dude just doesn't want to upload a build.
![image](https://user-images.githubusercontent.com/7742541/78851414-bd62da80-79e7-11ea-8822-aec302adf534.png)
