### ISSUE TITLE
Reclass.NET can´t type a simple underscore

### ISSUE THREAD

**Issue by B4nny2866** [ReClassNET/ReClass.NET#143]
I have a german keyboard and the latest reclass version everytime i trie to type a simple _ it replaces it with a space 
![image](https://user-images.githubusercontent.com/59650178/71990877-76bce300-3234-11ea-812e-60ba1763ab3d.png)

**Comment by KN4CK3R** [comment]
That's just a display problem because the input field is not big enough. As you can see the PE header is there so the module is found.
![grafik](https://user-images.githubusercontent.com/1666336/71995582-1bdaba00-323b-11ea-965b-d4a147afcee7.png)

**Comment by B4nny2866** [comment]
thanks for answering. It´s appearly only a visual bug and gets resolved when i type enter
