### ISSUE TITLE
Project doesn't build in VS 2017

### ISSUE THREAD

**Issue by meiskam** [ReClassNET/ReClass.NET#150]
@KN4CK3R 
Compiling instructions for this project suggest to use version 2017, but commit 8cee86ff has added features that only work in C# 8.0. I don't use C# very much, but it looks to me like VS 2017 is using C# 7.0.  Is there a way to get this to compile in 2017?

**Comment by Timboy67678** [comment]
you can install the latest c# compiler from nuget, should work on the reclas project https://www.nuget.org/packages/Microsoft.Net.Compilers/

**Comment by meiskam** [comment]
I've updated Microsoft.Net.Compilers to v3.4.0 with nuget, and also installed .NET 3.0 dev to work with that version.  Now the project refuses to load because I don't have v142 build tools.

https://stackoverflow.com/a/59141713 this seems to say that it's not possible to get v142 build tools in VS 2017?

**Comment by Timboy67678** [comment]
> I've updated Microsoft.Net.Compilers to v3.4.0 with nuget, and also installed .NET 3.0 dev to work with that version. Now the project refuses to load because I don't have v142 build tools.
> 
> https://stackoverflow.com/a/59141713 this seems to say that it's not possible to get v142 build tools in VS 2017?

im guessing thats to build the NativeCore, have you tried changing platform toolset to 141?

![image](https://user-images.githubusercontent.com/994534/75680806-113e1d80-5cde-11ea-9e14-9bcbf70a3e56.png)

after that, you will need to right-click the NativeCore project and re-target the SDK to the latest version you have installed

**Comment by meiskam** [comment]
I appreciate your help, but I've just rolled back to before the commit 12 days ago, and everything loads and compiles fine now.  There were too many errors for me to figure out how to get it working.

I think you're right, that the readme shouldn't suggest people download VS2017 and then go through this to get it working.

Thanks

**Comment by KN4CK3R** [comment]
Right, VS 2017 isn't enough anymore. I will update the readme.
