### ISSUE TITLE
"processname.exe+offset" syntax

### ISSUE THREAD

**Issue by bugproof** [ReClassNET/ReClass.NET#153]
![image](https://user-images.githubusercontent.com/3116731/76869568-d228d400-6868-11ea-89a1-6cf640133d25.png)

**Comment by KN4CK3R** [comment]
Syntax is `<processname.exe> + 0x500`
If that is not your question a little sentence may help.

**Comment by GH-Rake** [comment]
<Calculator.exe>+0x500

is the correct syntax

**Comment by bugproof** [comment]
It worked in my own build from master, but it crashes in the latest release build from https://github.com/ReClassNET/ReClass.NET/releases/download/v1.2/ReClass.NET.rar
