### ISSUE TITLE
Pointers Don't Show

### ISSUE THREAD

**Issue by Time-ghoul** [ReClassNET/ReClass.NET#161]
On the stable build of Reclass, pointers are displayed like this: 

![image](https://user-images.githubusercontent.com/30274499/86492935-39de2e80-bd35-11ea-9a32-fb9a2649a426.png)

But the current branch looks like this: 

![image](https://user-images.githubusercontent.com/30274499/86492891-13b88e80-bd35-11ea-9216-dd1bef9a6891.png)

**Comment by KN4CK3R** [comment]
Thank you for the report. Will be fixed in a few seconds.
