### ISSUE TITLE
This Thing

### ISSUE THREAD

**Issue by Rainwound** [ReClassNET/ReClass.NET#163]
![image](https://user-images.githubusercontent.com/30274499/87612571-8714b580-c6d0-11ea-8913-804debae7dab.png)

It builds when I remove that line, so yeah.

**Comment by KN4CK3R** [comment]
That works since the beginning. Maybe you made something wrong with the resources and `icon` is invalid?

**Comment by Rainwound** [comment]
I just download & compile. No changes. 

It's not exactly a big deal, because all it is is an icon. Just thought I'd let you know that it occurs

**Comment by KN4CK3R** [comment]
I have tested it in a clean environment and got no errors.
Win 10 with VS 2019 latest version and current master branch code

**Comment by Rainwound** [comment]
Odd. Must be something on my end then

**Comment by KN4CK3R** [comment]
Fixed in #168
