### ISSUE TITLE
Pointer cannot be expanded

### ISSUE THREAD

**Issue by bachvkhoa** [ReClassNET/ReClass.NET#165]
I'm new to ReClass, according to some tutorials, I have tried to change the type of an address to Pointer type
My ReClass (latest version) changed it but the pointer cannot be expanded.
The icon presentation also different as all tutorials.
What can I do to fix this or what did I'm wrong?
Thanks for your help.
I have tried on some addresses and some processes, but got the same results.
The image below is an example for my situation.
![2020-08-05 17_00_05-eclipse-workspace - kinrou_src_main_java_jp_co_kinrou_service_kintai_yojitu_sche](https://user-images.githubusercontent.com/22799418/89401137-0da43c00-d73f-11ea-9001-c8cebaacc5b7.png)

**Comment by KN4CK3R** [comment]
The pointer doesn't know the type it points to (`<void>`). Use the icon right to `<void>` to change the type to `Class Instance`. In later versions (you must compile ReClass.NET on you own) this is the default behaviour.

**Comment by bachvkhoa** [comment]
thank you very much
