### ISSUE TITLE
Pointer Not Automatically Allowing Expansion?

### ISSUE THREAD

**Issue by shoxter** [ReClassNET/ReClass.NET#166]
When reversing a program, setting an address to data type "pointer" doesn't allow for me to expand into that pointer's address. I then have to go to the repeat sign button, and click class (or something else) before I can expand. 

Am I missing something?

**Comment by KN4CK3R** [comment]
Maybe this is the same as in #165?

**Comment by shoxter** [comment]
> Maybe this is the same as in #165?

That's definitely it. I searched and didn't see that issue in the results. Silly me...... I'll close. My bad!
