### ISSUE TITLE
Ban when trying to Read Memory Using Reclass

### ISSUE THREAD

**Issue by hammad2224** [ReClassNET/ReClass.NET#167]
for unix you use process_vm_readv to read the memory 
this method is old and caught so we get ban during the reclass is running in pubg mobile.

can you add a Kernal Loadable Module in unix to read the memory so we dont get ban when working in reclass.net

**Comment by KN4CK3R** [comment]
This method is not "old", it's just the standard way on unix like ReadProcessMemory on Windows. You are free to implement a kernel plugin and publish it. I will add it to the plugin list then.
