### ISSUE TITLE
Latest ReClass isnt working for me

### ISSUE THREAD

**Issue by jcharnley** [ReClassNET/ReClass.NET#168]
Am trying to build the  git cloned solution on code 2019 using the latest .net release 528372 with the c++ sdk kit. for some reason when I try and open up the x86 exe and run it, it doesnt work. 

The only compling error I got was related to NativeCode .vcxproj, but have been told not to worry about it.

Upon starting i get this 
![Annotation 2020-08-30 145044](https://user-images.githubusercontent.com/25176118/91661755-d9216700-ead5-11ea-9edf-8a50d7e3f78f.png)

anyone has similar problems?

**Comment by KN4CK3R** [comment]
Could you please send a screenshot of the "Details" or even better, run ReClass.NET in the VS debugger. It should break on the exception and show more useful informations.

**Comment by jcharnley** [comment]
sure thanks for the quick reply

![Annotation 2020-08-30 151120](https://user-images.githubusercontent.com/25176118/91662033-bc862e80-ead7-11ea-917a-fdc744c73365.png)
![Annotation 2020-08-30 154413](https://user-images.githubusercontent.com/25176118/91662035-bdb75b80-ead7-11ea-9365-dadc62b7f023.png)

**Comment by KN4CK3R** [comment]
I have seen this error somewhere else but could not reproduce it at the time. Now I don't know where I got the report. For a quick fix just remove the `DrawImage` line. You loose the icons but no functionality. The error **may** be using a already disposed image. I will investigate this error if possible.

**Comment by jcharnley** [comment]
thanks that quick fix will do me, am just learning. thanks

**Comment by KN4CK3R** [comment]
I have found the error. This problem occurs while scaling icons if you have changed the DPI settings in Windows. I don't use scaling so the original image without the problem was used. Update your code to the last commit and the error should be gone.

**Comment by jcharnley** [comment]
that make sence yeah I have a big monitor and have changed my DPI setting so I can read !! thank you so much
