### ISSUE TITLE
Pointer not expanding

### ISSUE THREAD

**Issue by sn0x736e** [ReClassNET/ReClass.NET#171]
Pointer  to heap does not expand as in previous version from already compiled Release.NET v1.2 
![ts](https://user-images.githubusercontent.com/32274807/94528935-b6aa7700-0256-11eb-8790-41916938d6e8.PNG)

**Comment by KN4CK3R** [comment]
Have alook at #166.

**Comment by sn0x736e** [comment]
yeah thanks i found solution in closed shortly after :-x
