### ISSUE TITLE
x64 version missing "class ptr"

### ISSUE THREAD

**Issue by crvvdev** [ReClassNET/ReClass.NET#175]
Above there's a comparsion between the x64 (first one on top) and the x86 version, "class ptr" feature is missing on x64 version which in my opnion is a very strong and essential feature. 

![image](https://user-images.githubusercontent.com/70297450/96137774-6debf280-0ed3-11eb-934d-c22f08d6d458.png)

**Comment by KN4CK3R** [comment]
Where did you get the application files? The second screenshot shows an old version ReClass.NET.

In the first screenshot you can find the Pointer behind the `PTR` button (seventh icon from the right). A normal class instance is the `CLS INST` button.

**Comment by crvvdev** [comment]
The x64 version is compiled from master, the x86 version is the last stable release.

The change can be confusing for users that are familiar with the x86 version, but i'm glad this feature wasnt removed after all.

**Comment by KN4CK3R** [comment]
Both version are identical!
