### ISSUE TITLE
Requesting a new build

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#18]
:D? cant afford to install all the c# crap

**Comment by stevemk14ebr** [comment]
As abnoxious as that was written i do think it might be cool to have to the releases link: https://github.com/KN4CK3R/ReClass.NET/releases scripted to build off the repo. In my mind new commits would trigger a rebuild somewhere and the link would update for everyone, thoughts on how to do this @Timboy67678 or @KN4CK3R  or whoever

**Comment by I-MrFixIt-I** [comment]
I don't do much with GitHub, but Jenkins, Docker or maybe even TeamCity might be a solution?
We use SVN and TeamCity in business and it works quite well.

**Comment by Timboy67678** [comment]
we could probably use Travis-CI, a lot of open source projects use this as an automatic buildbot

**Comment by LWSS** [comment]
Bump, I use this a lot on linux but there's a lot of bugs that I think are patched in the master.

Building it is a bit cumbersome... I did try for *quite* a while, but the linux solution is setup for some remote server, idk what packages are used, and i'm not familiar with .NET.

**Comment by stevemk14ebr** [comment]
If we can get a common docker container to build on linux that'd be a walk in the park for new comers. Windows containers are trash though, a bat file might be better there

**Comment by KN4CK3R** [comment]
Duplicate of #100.
