### ISSUE TITLE
Unable to open tool strip menu in process info form

### ISSUE THREAD

**Issue by logankonopatzke** [ReClassNET/ReClass.NET#181]
I'm building 774ec6f on Ubuntu 18.04 and running with mono. After attaching to a process and opening the 'Process Informations' window, I try to right click to dump a module, but the dialog menu just doesn't show up. I also tried this same build on a different Ubuntu system and I have the same problem.

mono --version output: `Mono JIT compiler version 6.10.0.104 (tarball Fri Jun 26 19:38:24 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com`

The dialog menu I'm referring to (screenshot taken on my windows 10 machine):
![dialogmenu](https://user-images.githubusercontent.com/60406681/100550899-d6ecb700-3242-11eb-8714-ab7445241864.png)

**Comment by KN4CK3R** [comment]
Thank you for the report. I was able to fix it.

![grafik](https://user-images.githubusercontent.com/1666336/100553522-a6326f00-328e-11eb-873b-5b00321b0443.png)

**Comment by logankonopatzke** [comment]
Working as intended on my end, thank you for all your hard work on this incredible project!
