### ISSUE TITLE
Native Memprocfs support

### ISSUE THREAD

**Issue by rlewkowicz** [ReClassNET/ReClass.NET#183]
I'm fumbling around trying to write a plugin for Reclass (btw is there any good docs for that? Tips on building, troubleshooting, etc?) but it would be awesome if there was native support. It would allow reclass to work seamlessly with fpga devices

**Comment by Remashes** [comment]
Hey, I’ve found this https://github.com/mgoodings/ReClass.NET-PciLeechPlugin it’s outdated and I couldn’t  manage to update (don’t know a lot about vmmdll) but I hope you can.

**Comment by rlewkowicz** [comment]
Yea that's what I've been fumbling with. I'm an average developer as it is and not particularity skilled with C++. On top of that windows flavored c++ seems to have it's own sort of weirdness as compared to like gnu flavored C++. He made all the structs a lot more atomic now I have to figure out all the little sub types and what they represent. 

I also compiled that old plug and it didn't work so who knows if this even a good place to start

**Comment by Remashes** [comment]
The old plugin seems a good place to start, there are 2 functions that have changed on vmmdll.h fixing them I made ReClass show the process list from second PC but when I try to load modules it crashes, seems to be related with some error on the way I'm trying to create a modules entry map.

**Comment by rlewkowicz** [comment]
@Remashes did you compile reclass from source, or use a release? I've re written everything, and I think it's happy, but I can't even get my plugin to load. 
```
Program Location:

   at ReClassNET.Plugins.PluginManager.CreateNativePluginInstance(String filePath)
   at ReClassNET.Plugins.PluginManager.LoadPlugins(IEnumerable`1 files, ILogger logger, Boolean checkProductName)
```
It's failing on check product name

**Comment by rlewkowicz** [comment]
I missed the dlls for vvm and leechcore. As well as that one usb driver so it just died weird. It's all working now. what an adventure this has been

**Comment by Remashes** [comment]
Are you willing to share this? I haven't been able to solve the issue.

**Comment by Akandesh** [comment]
Updated fork: https://github.com/Akandesh/ReClass.NET-PciLeechPlugin
