### ISSUE TITLE
Failed to load native plugin

### ISSUE THREAD

**Issue by rlewkowicz** [ReClassNET/ReClass.NET#185]
I re wrote a large portion of this using an updated memprocfs library:

https://github.com/mgoodings/ReClass.NET-PciLeechPlugin

It compiles into a dll, everything seems happy, but it wont load:

===================================

Failed to load native plugin: PciLeechPlugin.dll (ReClass.NET)

------------------------------
For help, click: https://github.com/ReClassNET/ReClass.NET/issues

------------------------------
Program Location:

   at ReClassNET.Plugins.PluginManager.CreateNativePluginInstance(String filePath)
   at ReClassNET.Plugins.PluginManager.LoadPlugins(IEnumerable`1 files, ILogger logger, Boolean checkProductName)

**Comment by KN4CK3R** [comment]
The error you are getting just indicates that `LoadLibrary` fails. 

https://github.com/ReClassNET/ReClass.NET/blob/96b36cf7a97d41863b6d75098f681615884d55f7/ReClass.NET/Plugins/PluginManager.cs#L152-L156

Are you sure you don't try to load a x86 plugin while running ReClass.NET in x64 mode or vice versa?

**Comment by rlewkowicz** [comment]
@KN4CK3R turns out I missed the needed dlls to the x64 folder of reclass. I accidently copied the header files instead because my brain is spaghetti. It's all working! I can enumerate and attach to processes through my fpga device. very cool.
