### ISSUE TITLE
ReadNodeInfo--->nodeAddress==0 ???

### ISSUE THREAD

**Issue by huangfengye** [ReClassNET/ReClass.NET#198]
it look like in
ReadNodeInfo(BaseHexCommentNode node, IRemoteMemoryReader reader, MemoryBuffer memory, IntPtr nodeAddress, IntPtr nodeValue)
i can only get nodeValue.  nodeAddress always zero???

in BFV , some ptr have diffrent way to get typeinfo...
in this pic, i don;t need nodeValue (0x143AEB4A0), but i need get this ptr 0x144F7A060.

In my understanding ， the nodeAddress should be 0x13FC0C650, so i can use ReadRemoteIntPtr(0x13FC0C650+8) to get 0x144F7A060

 ![image](https://puu.sh/HO2Fm/9176b801bc.png)

in this pic , u can see if i get 0x144F7A060,  i will have the ptr typeinfo..
 ![image](https://puu.sh/HO2HN/62ca0662cb.png)

**Comment by KN4CK3R** [comment]
I don't understand what you are talking about.
https://github.com/ReClassNET/ReClass.NET/blob/d95a424ffdd1d0b8183e4f1c3f4f18968393040b/ReClass.NET/Nodes/BaseHexCommentNode.cs#L97-L101
So `nodeAddress` will never be zero.

Are you trying to do this:
https://github.com/ReClassNET/ReClass.NET-FrostbitePlugin/blob/master/FrostBiteNodeInfoReader.cs

**Comment by huangfengye** [comment]
I will check more, btw ReClass.NET-FrostbitePlugin not work on BFV.
this is a simple fix
```cpp
private static string ReadPtrInfo(IntPtr value, IRemoteMemoryReader process)
{
            var vtable = process.ReadRemoteIntPtr(value);
            byte[] jmpinst = process.ReadRemoteMemory(vtable,sizeof(byte));
            var getTypeFnPtr = process.ReadRemoteIntPtr(value);
            if (jmpinst[0] == 0xE9)
            {
                var offsetjmp = process.ReadRemoteInt32(vtable + 1);
                getTypeFnPtr = vtable + offsetjmp + 5;
            }
            if (getTypeFnPtr.MayBeValid())
		{
#if RECLASSNET64
			var offset = process.ReadRemoteInt32(getTypeFnPtr + 3);
			var typeInfoPtr = getTypeFnPtr + offset + 7;

#else
			var typeInfoPtr = process.ReadRemoteIntPtr(getTypeFnPtr + 1);
#endif
			if (typeInfoPtr.MayBeValid())
			{
				var typeInfoDataPtr = process.ReadRemoteIntPtr(typeInfoPtr);
				if (typeInfoDataPtr.MayBeValid())
				{
					var namePtr = process.ReadRemoteIntPtr(typeInfoDataPtr);
					if (namePtr.MayBeValid())
					{
						var info = process.ReadRemoteStringUntilFirstNullCharacter(namePtr, Encoding.UTF8, 64);
						if (info.Length > 0 && info[0].IsPrintable())
						{
							return info;
						}
					}
				}
			}
		}

			return null;
}
```



> I don't understand what you are talking about.
> https://github.com/ReClassNET/ReClass.NET/blob/d95a424ffdd1d0b8183e4f1c3f4f18968393040b/ReClass.NET/Nodes/BaseHexCommentNode.cs#L97-L101
> 
> 
> So `nodeAddress` will never be zero.
> Are you trying to do this:
> https://github.com/ReClassNET/ReClass.NET-FrostbitePlugin/blob/master/FrostBiteNodeInfoReader.cs
