### ISSUE TITLE
Arrays of primitive datatypes?

### ISSUE THREAD

**Issue by ghost** [ReClassNET/ReClass.NET#21]
Hi, how to create arrays for primitive datatypes like int32 for example or float or whatever?
I mean I could just put two int32 in row but they must have different names then... or I would have to create a new class with two int32 members which is also crappy.

**Comment by KN4CK3R** [comment]
Currently such a type is not implemented. This is already on my todo list (I thought there was an issue about that too but doesn't look like).
A workaround is an ArrayNode with a class which contains only a Int32Node.

**Comment by Yothri** [comment]
Allright, thanks, yeah I was just asking because maybe I am just too dumb to find it but if its really not implemented then I take the workaround. Thanks for the lightning answer!

**Comment by KN4CK3R** [comment]
The array type has the same problems as #22 .

**Comment by johmarjac** [comment]
Any news on this?

**Comment by KN4CK3R** [comment]
> 
> 
> Any news on this?

This is now implemented in the NodePointer branch but it is not ready to be merged in master.

**Comment by KN4CK3R** [comment]
This feature is implemented in the master branch now.
