### ISSUE TITLE
Add unhide all or a way to unhide child nodes of class

### ISSUE THREAD

**Issue by Guusggg** [ReClassNET/ReClass.NET#211]
Hi,

Today I encountered something that I didn't expect. I mistakenly hid all the 4 members of a class and I'm not in ANY way able to unhide them. I don't want to start over as it's a String class that's all throughout the classes that I unpuzzled. 

Would it be possible to add an Unhide All feature or let us be able to right click Classes in the editor? 

I tried adding bytes, nope. I tried right-clicking the class anywhere in the program, but no context menu pops up.

Thank you for reading.
Kind regards,

**Comment by KN4CK3R** [comment]
![grafik](https://user-images.githubusercontent.com/1666336/142779937-c550c250-4373-454f-b748-7b30650431ac.png)
There is already a command in the context menu.

**Comment by Guusggg** [comment]
Okay, thank you so much for the comment! I was aware of the context menu options but my problem is that I'm unable to get the actual context menu to pop up. Do you use any special mouse or anything? ;)

**Comment by KN4CK3R** [comment]
Do you use the current master branch or the pre-compiled release?

**Comment by Guusggg** [comment]
I'm using the lated release which is currently ReClass.NET v1.2 Latest, released on 15 Apr 2019.
As I checked it, it's pretty old so might it be a good idea to compile it myself? Or would it be possible to make a more recent build as a new release?

Thanks for your time, I appreciate it

**Comment by ShadyXVX** [comment]
> I'm using the lated release which is currently ReClass.NET v1.2 Latest, released on 15 Apr 2019. As I checked it, it's pretty old so might it be a good idea to compile it myself? Or would it be possible to make a more recent build as a new release?
> 
> Thanks for your time, I appreciate it

If you need an updated build and don’t want to compile it yourself, guidedhacking has the most recent version for download. (I hope it’s allowed to name the site)

**Comment by Guusggg** [comment]
Not a problem, I don't really want to trust a site that's main purpose is hacking so I assume you understand my position of not dowloading a build there. I will compile it later this weekend for myself and make a pull request for a new release if you'd like. 

I'll let this issue rest for now and see if it pops up after I get a more recent version.

Thanks a lot guys
