### ISSUE TITLE
Add pointer to native types node

### ISSUE THREAD

**Issue by KN4CK3R** [ReClassNET/ReClass.NET#22]
Add a new node type which represents a pointer to native types (int*, float*, Matrix*, ...) not just classes.

Theorectical Problems: ArrayNode, Serialization, Pointer to nothing (void*) ?

**Comment by KN4CK3R** [comment]
I have implemented this in the [PointerNode branch](https://github.com/ReClassNET/ReClass.NET/tree/PointerNode). There is now a PointerNode and an ArrayNode which can wrap any other type.

![grafik](https://user-images.githubusercontent.com/1666336/51975314-2bc21980-2482-11e9-977f-fe702fbf863e.png)

@Timboy67678 @stevemk14ebr @ajkhoury: Opinions?

Here is the project file from the screenshot:
[pointers.rcnet.zip](https://github.com/ReClassNET/ReClass.NET/files/2812114/pointers.rcnet.zip)

The last problem I have is the code generation. I failed to come up with a system which
- is flexible enough for multiple languages (C++, C#, ...)
- supports custom nodes from plugins

Desired structure:
```
Nodes -> ??? -> C++
          |
          |---> C#
```
`???` exists currently as [MemberDefinition](https://github.com/ReClassNET/ReClass.NET/blob/PointerNode/ReClass.NET/CodeGenerator/MemberDefinition.cs). But the class is not flexible enough for multiple code targets and wrapper nodes. To support wrapped nodes there should be a `MemberDefinition InnerDefinition` and `IsPointer` / `IsArray`. Normal C++ types aren't a problem then but custom nodes don't work. How should a UE "TArray<>" be encoded in this structure? The type isn't static anymore so there needs to be a method which computes the type. How should this work for multiple target languages? Then the `MemberDefinition` isn't decoupled from the language...
I need your help here. :confused:

**Comment by Timboy67678** [comment]
fuck i didn't see this until now, sorry mate. 

ill have to have a look at some point, are c++ and c# the only languages you want to support in the code generation?

**Comment by KN4CK3R** [comment]
I think what I expect is a little bit out of scope. Looks like it is "not possible" ™ to create an AST structure which can serve it all (http://www.ii.uib.no/~karltk/projects/pli-ast.html , https://softwareengineering.stackexchange.com/questions/306941/is-an-ast-enough-to-build-any-translator).
For the memory nodes, the plugin needs to know for which language it should output code, so I will remove the abstraction (`MemberDefinition`) here. The plugin needs to provide something like `IDictionary<Language, Serializer> GetCodeSerializer()` which can create the node decleration in the supported languages.

**Comment by KN4CK3R** [comment]
This feature is implemented in the master branch now.
