### ISSUE TITLE
Class Pointer not available

### ISSUE THREAD

**Issue by supernghia89** [ReClassNET/ReClass.NET#231]
![image](https://user-images.githubusercontent.com/15607260/174713476-3f3f51f9-a6b6-436e-b8f1-8b95f1109e8e.png)

There are no Class pointer, so how I can show the pointer as a class

Thanks

**Comment by KN4CK3R** [comment]
In your screenshot 3 elements above.

**Comment by supernghia89** [comment]
Got it. Thank you
