### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by fantatik3** [ReClassNET/ReClass.NET#233]
When you make an an array, ex: Arr[2] and you access index 1, if then you edit the array to be size 1, the program will crash, if somehow you saved the file, your class will become corrupt.

**Comment by KN4CK3R** [comment]
I can't reproduce the exception but fde1599 limits the array index now. Did you compile ReClass with the newest code?

**Comment by fantatik3** [comment]
Yep, updated the source yday, ill make a video later on how to reproduce the issue.

Cheers

**Comment by fantatik3** [comment]
Sent the .rcnet file thru email, to reproduce just click sGDATA class.

**Comment by KN4CK3R** [comment]
The problem has nothing to do with the array index. You use excessive amounts of array nodes. For example this one in the sGDATA class.

![grafik](https://user-images.githubusercontent.com/1666336/183925962-48d911e7-263e-476d-a7fc-d35681195f42.png)

There are three array nodes stacked into each other which means the outer array needs `2416*1*2416*(size of inner node)` bytes. And I have seen other nodes with more than 6000 items.

So sure, this needs a lot of memory which may not be available. I don't think there is much I can do if you tell the program to allocate x memory which is not available.

**Comment by fantatik3** [comment]
Im just investigating some game structs that i dont know much of so i tend to make big arrays to check in this case for game files. Maybe i went too large or set an extra 0 since that was the last part i was listing.
