### ISSUE TITLE
Incorrect if/else stagment

### ISSUE THREAD

**Issue by boris768** [ReClassNET/ReClass.NET#240]
https://github.com/ReClassNET/ReClass.NET/blob/fde15991a5fe7b6a309053ca2b71f557b820c260/ReClass.NET/Util/Rtf/RtfBuilder.cs#L259-L266

'\t' symbol is 9, which always satisfies the first condition.

**Comment by KN4CK3R** [comment]
Thanks! Did you run into a problem or how did you find that?

**Comment by boris768** [comment]
> Thanks! Did you run into a problem or how did you find that?

Found by PVS-Studio, highly recommended for use
