### ISSUE TITLE
Reclass does not attach to process on linux (Ubuntu 22.04/ Debian 11 / Arch linux) (Freezes)

### ISSUE THREAD

**Issue by AIVDNL** [ReClassNET/ReClass.NET#242]
Reclass runs correctly after building for linux x64, and runs correctly using `mono /bin/Release/x64/ReClass.NET.exe `

However, attaching to a process causes Reclass to freeze. I've tried rebuilding the solution and different VMs, but the result persists. It will not attach and immediately freeze.

FWIW` /proc/sys/kernel/yama/ptrace_scope` is set to 0. (I've tried different values)

**Comment by AIVDNL** [comment]
Also, building on linux 20.04 using docker gives me Failed to load native functions! Couldn't find at location x64/x86 NativeCore.so  while the file is clearly there. maybe something to do with mono?

Anyway I cannot get reclass to function correctly either because it does not run *20.04 or because it won't attach to a process (immediately freezes) * 22.04

**Comment by ihateadmins** [comment]
NativeCore.so exception might be related to https://github.com/ReClassNET/ReClass.NET/issues/241
i don't have any issue at all with the x64 version.
Also mono compiled with multilib didn't make any difference to it either.

**Comment by AIVDNL** [comment]
You use Ubuntu 22.04? I've tried different tools that attach to processes (GameConqueror) and they attached just fine. not sure where the issue lies. If you have any idea if and where there are log files, I'd be happy to post them.

**Comment by AIVDNL** [comment]
Following #47 to build on Debian 11 works, but this will also freeze when trying to attach to a process. really confused here.

**Comment by AIVDNL** [comment]
Running with gdb attached gives the following error when attaching: thread 4 "mono" received signal SIG35, Real-time event 35.
[Switching to Thread 0x7fffec9e7640 (LWP 14724)]
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x7fffec9e6be0, op=137, expected=0, futex_word=0x5555559fd888) at ./nptl/futex-internal.c:57
57	./nptl/futex-internal.c: No such file or directory.

**Comment by AIVDNL** [comment]
Also tried on  Arch Linux - also freezes.

**Comment by nekiter** [comment]
Same problem here, but on Manjaro.

Build the current version of this repo.

**Comment by qb-0** [comment]
Same here. PopOs

**Comment by cassanof** [comment]
Same problem on Arch Linux.

**Comment by EricYoong** [comment]
Anyone got the solution for this? I also having this issue on Ubuntu 22.04

**Comment by damajor** [comment]
Same on Fedora 37
