### ISSUE TITLE
Can't Load .RCNET Project Files

### ISSUE THREAD

**Issue by iAemmx** [ReClassNET/ReClass.NET#249]
I'm trying to open a .rcnet file (which i'm inspected is a zip file containing an xml with the definitions of the classes and enums) and every time I try to open it with new project or merging it is:

The input is not a valid Base 64 string because it contains a non-Base 64 character, more than two padding characters, or an invalid character between the padding characters. (mscorlib)

but the XML is rightly formed, is there a possibility to import the xmls directly?

**Comment by KN4CK3R** [comment]
Could you provide the stacktrace of the error? Could you check the XML for unusual Base64 strings?

**Comment by iAemmx** [comment]
Well, seems that i found part of the problem...

The program is looking for a BASE64 string in the uuid attribute of the classes tags, what i got in the file is an uuid with a CLSID identifier like this

    <class uuid="a1d8b4ef-9989-4749-abcd-b268041f01fd" name="RemotePlayerData" comment="" address="140000000">
      <node type="ArrayNode" name="m_data" comment="" hidden="false" count="32">
        <node type="ClassInstanceNode" name="N0000E350" comment="" hidden="false" reference="44a917ee-f013-4b4a-81ce-f044bb25b318" />
      </node>
      <node type="UInt32Node" name="m_count" comment="" hidden="false" />
      <node type="Hex32Node" name="N0000E354" comment="" hidden="false" />
    </class>

Still don't know if the rcnet was built with a personalized plugin or a ghost build of the application

**Comment by KN4CK3R** [comment]
Yes, the reference fields are GUIDs. Could you attach/upload the file you can't load?

**Comment by iAemmx** [comment]
here it is... hope you could guide me for make it usable 

[gtavRETutorial.zip](https://github.com/ReClassNET/ReClass.NET/files/10714506/gtavRETutorial.zip)

**Comment by KN4CK3R** [comment]
I can load the file without problems:
![grafik](https://user-images.githubusercontent.com/1666336/218278395-76058ad1-c0fa-47d3-8830-9400f9da0e90.png)

**Comment by iAemmx** [comment]
Thank You but i'm still having issues, could you confirm what are the requirements for executing the app in windows 10/11? i've downloaded the binaries from the link (not compiled nor built the code), no plugins installed ,i have .net framework 4.8.1 runtime (not developer) installed, MVC++ 2015-2019 runtime ver 14.28.29325, win 10 22H2 buil 19045.2486

i believe i'm missing something...
