### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by zaryar** [ReClassNET/ReClass.NET#253]
I tried to compile ReClass with those settings:
![image](https://user-images.githubusercontent.com/46141276/230359009-bd1d0bae-bd21-468d-8232-e826d12190c6.png)

but it does not seem to work, I get his error:
![image](https://user-images.githubusercontent.com/46141276/230359600-59b856e8-82c0-4063-be54-d6441d3b6792.png)

I digged a bit and I think its because the NativeCore does not compile? Anyone has any Idea?

**Comment by KN4CK3R** [comment]
How did you obtain the source code? Did you use git or just downloaded a source archive?

**Comment by zaryar** [comment]
I used $git clone https://github.com/ReClassNET/ReClass.NET.git

do I need some dependencies I dont have?

**Comment by KN4CK3R** [comment]
If you don't need unix support, you can disable/unload that project in VisualStudio.

**Comment by KN4CK3R** [comment]
The unix project uses the WSL subsystem to compile the code in an unix context. If the system is not available for VisualStudio you may get a more or less descriptive error message. 🤷‍♂️
