### ISSUE TITLE
Add a void* pointer datatype

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#27]
a void* type would be a nice idea, we already have a bool type ;D

example

```
class CPtrHandle
	{
	public:
		void* Ptr; //0x0000
		__int32 Handle; //0x0008
		char _pad0[0x4];

	};
```

**Comment by KN4CK3R** [comment]
Will be added as a "Pointer to None" with #22.

**Comment by KN4CK3R** [comment]
Is implemented in the master branch now.
