### ISSUE TITLE
Make invalid double click collapse nodes

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#30]
if you double click on the area away from the text of a node, make it collapse 
example:
https://i.imgur.com/o8OzxXj.png
if u double click right now it would collapse that node

**Comment by KN4CK3R** [comment]
Does not collapse for me. The click area is some pixel bigger than the icon but that's expected.

**Comment by KittoniuM** [comment]
i mean, you should add a feature so it collapses if you click it
