### ISSUE TITLE
Modify Text8 and Text16

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#36]
It would be good if you can change your Text8 and Text16's like you would a float or int

**Comment by KN4CK3R** [comment]
You can edit strings now. __BUT__ you need to make sure you don't destroy the string! If you change the length of the string the ending null character may get overwritten and everything is broken. Special characters which do not exist in the current encoding are replaced with dots. So if you edit the string all original special characters are replaced with real dots in the remote process. The next problem is the readonly memory where strings usally are placed. You may have write access there but the write can fail. So editing of strings works but I don't recommend it.
