### ISSUE TITLE
Use type definition as the display name

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#51]
had an idea earlier..

https://i.imgur.com/uU0PeDy.png

instead of "Int32" it should use the thing you defined it as, such as int32_t being the default

**Comment by KN4CK3R** [comment]
May be optional but not a default.
namespace::my_custom_type<4>::type instead of Int32 doesn't look so pretty.

**Comment by KN4CK3R** [comment]
I will not add this feature because other strings take to much space, especially for wrapped nodes.
