### ISSUE TITLE
Ability to change the a pointer address

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#53]
Add a ability or right click option to change the value of a pointer so you don't have to set it to Int32/Int64 and change that..

**Comment by stevemk14ebr** [comment]
I agree this would be useful. @KittoniuM would you like to submit a PR for any of your many feature requests?

**Comment by KittoniuM** [comment]
i can only submit a digital drawing of healthbars

**Comment by KN4CK3R** [comment]
Should be kept in mind for #22.
