### ISSUE TITLE
Ptr** and __int32* -- HOW?

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#58]
Hi, was just reading some combat arms SDK and I see this

https://i.imgur.com/9DJZ5T1.png

how did they make a CSpecialFx** member? how the heck did they make a __int32*?? can you do this in reclass net?

**Comment by KittoniuM** [comment]
![Image of Bick](https://i.imgur.com/9DJZ5T1.png)

(sorry, cant edit the main post :))

**Comment by Timboy67678** [comment]
maybe they did it by hand or used a custom type???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by KN4CK3R** [comment]
Will be possible with #22.
