### ISSUE TITLE
Add a progress bar when loading 

### ISSUE THREAD

**Issue by fisherwise** [ReClassNET/ReClass.NET#62]
Since it usually takes a long time loading project file, it's better to add a progress bar instead of "no responding"

**Comment by KN4CK3R** [comment]
I don't think the loading of the project is the problem but the class list on the left side. I will see how I can speed this up.

**Comment by KN4CK3R** [comment]
I have added a fix. Please test if your files are loaded faster now.

**Comment by fisherwise** [comment]
It is indeed 100000 times faster!
I have ~100 classes and it used to take me ~1 min to load. Now it's ~2 seconds
