### ISSUE TITLE
Long loading time when creating class pointer / renaming class

### ISSUE THREAD

**Issue by fisherwise** [ReClassNET/ReClass.NET#63]
Hi. Just another loading issue.
Currently I'm facing long loading time when creating class pointer / renaming class. Is that possible to fix this as well?

**Comment by KN4CK3R** [comment]
Could you upload the file for testing? I don't have such big and/or complex files atm. If the file should not be public you can send me a mail to admin{at}oldschoolhack.me

**Comment by KN4CK3R** [comment]
Thank you for the test file. The problem is again the class list in the sidebar. It will faster without the hierarchical view. I will try find the root of the problem.

**Comment by fisherwise** [comment]
Actually it takes longer on my end to create a class / assign it to existing class / Rename a class using the latest commit

**Comment by fisherwise** [comment]
Is there a quick workaround? It's taking me ~3min to change the name of a class

**Comment by fisherwise** [comment]
thanks that do help!

**Comment by KN4CK3R** [comment]
I can't fix the error because it is by design. I disabled the hierarchy view by default now which should fix the performance problems. I don't think this feature was widly used so that should be ok for now.
