### ISSUE TITLE
How to do Pointer Preview for each row

### ISSUE THREAD

**Issue by stark11er** [ReClassNET/ReClass.NET#66]
Hello KN4CK3R, First of all I want to express my gratitude for this software. I liked the UI design and good code quality.

And the question. I want modify code for myself than Pointer Preview popup work for each row. I need this this, because i use read/write kernel driver, and i dont know where exactly is pointer.

I try to find this in MemoryPreviewPopUp & HotSpot classes. Tell me please, where can I find this code verification for pointer. Thx!

**Comment by KN4CK3R** [comment]
Just modify Node.UseMemoryPreviewToolTip for Hex32/64Node and return true every time.

**Comment by stark11er** [comment]
thx man for help!
