### ISSUE TITLE
Broken form designer?

### ISSUE THREAD

**Issue by cursey** [ReClassNET/ReClass.NET#67]
I'm no expert on C# and .NET so maybe I've missed something completely obvious but when I try to open up the forms in this project in design mode (`MainForm.cs` for example) I'm greeted by this lovely screen:

![image](https://user-images.githubusercontent.com/5798459/40587266-a3249300-6181-11e8-9cb8-be951f506caf.png)

This happens for every form I've tried. Any idea why this is happening?

I'm using the latest Visual Studio 2017 and I have the C# for desktop applications packages installed. The project compiles fine.

**Comment by Timboy67678** [comment]
i believe this has something to do with the latest visual studio (2017 community) not displaying the forms properly.  I think @KN4CK3R uses something older

**Comment by KN4CK3R** [comment]
No I use the latest version but Visual Studio itself is the (known) problem. Visual Studio is a 32bit app and the designer works by compiling and displaying your form class. You have selected the x64 build mode which forces the compiler to compile the (form) classes in 64bit mode. Now the 32bit designer needs to load a 64bit assembly which fails and results in this error. Simply switch to x86 build mode and everything will work.

**Comment by KN4CK3R** [comment]
Here are more infos:

https://stackoverflow.com/questions/5378919/visual-studio-designer-in-x64-doesnt-work
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/2677962-make-design-view-available-for-x64-target-platform

**Comment by cursey** [comment]
Thanks for the quick response.
