### ISSUE TITLE
Attach process selector can't find all the PIDs

### ISSUE THREAD

**Issue by korcankaraokcu** [ReClassNET/ReClass.NET#69]
ReClass.Net is missing the exectuable I'm trying to attach into

**Comment by Timboy67678** [comment]
do you have filter process's on? Are you running reclass as administrator?

**Comment by korcankaraokcu** [comment]
I'm running it as admin and no, I don't have the `exclude common processes` button checked. Still doesn't work

**Comment by Timboy67678** [comment]
are you running the correct version of reclass for your executable ur targeting? (x86 version of reclass only targets x86 process's and vise versa)

**Comment by korcankaraokcu** [comment]
I thought it was just the binary version 😄 It solved my issue, thanks. Have a good day
