### ISSUE TITLE
Find out what accesses this address does not work

### ISSUE THREAD

**Issue by FaBeyyy** [ReClassNET/ReClass.NET#70]
Tried using it with a real game example and a simple application I wrote.
Works with cheat engine on both occasions doesn't work with ReClass.NET

**Comment by FaBeyyy** [comment]
```
struct Test
 {
	float a = 0;
 };

int main()
{
	auto test = std::make_unique<Test>();

	for (int i = 0; i < 1000; ++i)
	{
		test->a = 1337+i;
		std::cout << test->a << std::endl;
		Sleep(5000);
	}

	return 0;
}
```
[Video](https://streamable.com/g4cyf)

**Comment by KN4CK3R** [comment]
I don't think that's the real problem but your video can't work because you try to attach two debuggers to a process.

**Comment by FaBeyyy** [comment]
You are right with both statements it doesnt work with reclass only either.

**Comment by KN4CK3R** [comment]
It doesn't work for me too so I must have broken it some time ago. I will let you know when I have fixed it.

**Comment by FaBeyyy** [comment]
Alright. Thanks for the quick help :)

**Comment by KN4CK3R** [comment]
Please test again, should work now.

**Comment by FaBeyyy** [comment]
Works with the test application. Probably doesn't work with the game because EAC is doing some anti debugging shit. Thanks alot though!
