### ISSUE TITLE
[Request] Ability to use the modules name when entering address

### ISSUE THREAD

**Issue by johmarjac** [ReClassNET/ReClass.NET#72]
Hi,

I think it would be a nice feature if it would be possible to enter the name of the module into where you put the address when you attach to a process:

![image](https://user-images.githubusercontent.com/30114127/43205196-23c101c2-9023-11e8-8e09-3a28b7c8e990.png)
Like this for example. So internally it takes the modules base address.

Is that doable?

**Comment by Timboy67678** [comment]
this is actually already a feature, see https://github.com/ReClassNET/ReClass.NET#tips

**Comment by johmarjac** [comment]
Works like a charm! Thanks for the hint! :)
