### ISSUE TITLE
Plugin Problem

### ISSUE THREAD

**Issue by koodpzok** [ReClassNET/ReClass.NET#76]
I lose the ability to see the processes after i used the plugin. Prior to that, i could see all the processes to attach. I only tested on two plugins, Handle Abuser, SimpluePluginNative. It happened to both of them.
![default](https://user-images.githubusercontent.com/20734022/48768971-1182f700-eced-11e8-8150-8337a64a7b3b.png) 
![default](https://user-images.githubusercontent.com/20734022/48768988-1ba4f580-eced-11e8-8da6-8a049165aa25.png)

**Comment by KN4CK3R** [comment]
That's like it should be. The HandleAbuser needs a second process which provides the handles to abuse so it will only list informations from this second process (https://github.com/ReClassNET/ReClass.NET-HandleAbuser/blob/master/Plugin/HandleAbuserPluginExt.CoreProcessFunctions.cs#L177). It looks like you don't have this other process started so no process shows up.

And the native sample plugin is just a code skeleton to help developers. It has an empty EnumerateProcesses method which simply does nothing (https://github.com/ReClassNET/ReClass.NET-SamplePlugin/blob/master/Native/dllmain.cpp#L7). So no process is shown which is fine too.

To use the basic methods of ReClass.NET just use the default function provider.

**Comment by koodpzok** [comment]
thank you sir, the process already showed up. I have one more question. When i injected the PipeServer.dll into cheat engine.exe. the process showed up with no  problem. But when i injected PipeServer.dll into my custom made process (This is HandleMaster_d.exe that used OpenProcess to another process), the process didnt show up in the attach list of ReClass.NET.
