### ISSUE TITLE
Pointer Array of Class Pointer

### ISSUE THREAD

**Issue by johmarjac** [ReClassNET/ReClass.NET#78]
Hi,

unfortunately it seems that the Array of Pointer Node does only support Class Instances. I need an Array of Pointer where every Pointer points to another Pointer of a specific class.

I know that you (@KN4CK3R ) know the Unreal Engine so you are aware of the TArray<T> struct.
Imagine the `ULevel::Actors` member which is a `TArray<AActor*>`

I wanted to create a class in ReClass that is able to visualize exactly this. The first member in the `TArray` is a Pointer to the Pointer Table. However I am only able to put another class which is already defined in the Array of Pointers instead of a here required Class Pointer of AActor.

Do you get what I mean?

Is it possible to implement that?

Thanks in advance

**Comment by KN4CK3R** [comment]
Since the classes don't allow templates (would be a cool feature btw) the easiest solution would be a custom node. There is a private repository which contains an Unreal Engine plugin for ReClass.NET with that functionality. Maybe I can post the code of the class here this weekend.

**Comment by johmarjac** [comment]
Would be dope. Thanks :)
For now I just created another class which I basically called AActor* which holds then the Pointer to AActor... Not perfect but yeah working! :)

Thanks for ur work

**Comment by KN4CK3R** [comment]
Here is the new plugin: https://github.com/ReClassNET/ReClass.NET-UnrealEngineClassesPlugin
I have only added some structs but they are not registered in ReClass.NET yet. So currently the plugin is not usable.

**Comment by johmarjac** [comment]
@KN4CK3R Thanks anyways I will have a look. Are you going to further work on this or unlikely?

**Comment by KN4CK3R** [comment]
I will go further on the plugin but it is more like a "so you can do it" project to encourage other developers to contribute to it.

**Comment by KN4CK3R** [comment]
Classes like TArray are now possible as custom nodes.
