### ISSUE TITLE
Tips and Tricks

### ISSUE THREAD

**Issue by KittoniuM** [ReClassNET/ReClass.NET#79]
wouldbe nice if there was a window or Windows Help for tips and tricks to help people find things like entity lists, viewmatrixes, etc.

example would be:

"You can find waypoint vector address by searching for the string of distance like "%i M" in Ida and then look at the formatting arguments"

**Comment by KN4CK3R** [comment]
That has nothing to do with ReClass because it is specific to a (single) game.
