### ISSUE TITLE
Doesn't run on linux (Kubuntu 18.10), but compiles without any issues

### ISSUE THREAD

**Issue by FilipeSilvens** [ReClassNET/ReClass.NET#83]
`Unhandled Exception:
System.IO.FileNotFoundException: Failed to load native core functions! Couldnt find at location /home/shiruba/ReClass.NET/ReClass.NET/bin/Debug/x64/NativeCore.so`

Compiled and then moved the NativeCore shared object to the directory of the executable and ran it with mono (tried with root as well).

Distro: Kubuntu 18.10
Mono version: 5.18.0.225

**Comment by KN4CK3R** [comment]
That's the same problem I had in #47 or? If so, I haven't figured out what the problem was/is. Maybe dlopen can't load a dependency?

**Comment by FilipeSilvens** [comment]
Does it successfully import libdl.so?

**Comment by KN4CK3R** [comment]
I think so. dlopen just returns IntPtr.Zero. Are you able to compile ReClass.NET? You could add a dlerror call to see if the error message tells something usefull.

The new code could look like this:
```csharp
public IntPtr LoadLibrary(string fileName)
{
	var handle = dlopen(fileName, RTLD_NOW);
	if (handle.IsNull())
	{
		throw new ...Exception(dlerror());
	}
	return handle;
}
```
With the equivalent for Windows and GetLastError (or better use DllImportAttribute.SetLastError). After that
https://github.com/ReClassNET/ReClass.NET/blob/b22d79bfcad6d37d6d3f5b386297921b81a640dc/ReClass.NET/Core/InternalCoreFunctions.cs#L52-L56
and
https://github.com/ReClassNET/ReClass.NET/blob/b22d79bfcad6d37d6d3f5b386297921b81a640dc/ReClass.NET/Plugins/PluginManager.cs#L136-L140
should be changed to use the exception.

**Comment by FilipeSilvens** [comment]
Yes, as I stated in the title, I am able to compile.

The code you have provided does not compile due to the fact that IntPtr doesn't contain the IsNull definition.

`error CS1061: 'IntPtr' does not contain a definition for 'IsNull' and no extension method 'IsNull' accepting a first argument of type 'IntPtr' could be found`

**Comment by FilipeSilvens** [comment]
Running the program with "sudo MONO_LOG_LEVEL="debug" MONO_LOG_MASK="dll" mono ReClass.NET.exe" printed some more interesting information:

https://gist.github.com/FilipeSilvens/f373e89453ecc084cf65af08e15d29ae

**Comment by KN4CK3R** [comment]
The logged exception is just the exception you have created or not?

**Comment by FilipeSilvens** [comment]
It is. I replaced the LoadLibrary code with this:

```c#
        public IntPtr LoadLibrary(string fileName)
        {
            dlerror(); // clears any previous errors
            var handle = dlopen(fileName, RTLD_NOW | RTLD_GLOBAL);
            var errorPtr = dlerror();
            if (errorPtr != IntPtr.Zero) 
            {
                throw new Exception("dlopen exception: " + Marshal.PtrToStringAnsi(errorPtr));
            }
            return handle;
        }
```

and imported dlerror, of course.

**Comment by stevemk14ebr** [comment]
I never got past failing to open NativeCore.so it's always not found for me, so yea it's related to #47 

> Unhandled Exception:
System.IO.FileNotFoundException: Failed to load native core functions! Couldnt find at location /home/steve/Desktop/ReClass.NET/ReClass.NET/bin/Debug/x86/NativeCore.so
  at ReClassNET.Core.InternalCoreFunctions.Create () [0x0003e] in <f9d5c992783f4cb69a111f6b34a7123f>:0 
  at ReClassNET.Core.CoreFunctionsManager..ctor () [0x00013] in <f9d5c992783f4cb69a111f6b34a7123f>:0 
  at ReClassNET.Program.Main (System.String[] args) [0x00097] in <f9d5c992783f4cb69a111f6b34a7123f>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Failed to load native core functions! Couldnt find at location /home/steve/Desktop/ReClass.NET/ReClass.NET/bin/Debug/x86/NativeCore.so
  at ReClassNET.Core.InternalCoreFunctions.Create () [0x0003e] in <f9d5c992783f4cb69a111f6b34a7123f>:0 
  at ReClassNET.Core.CoreFunctionsManager..ctor () [0x00013] in <f9d5c992783f4cb69a111f6b34a7123f>:0 
  at ReClassNET.Program.Main (System.String[] args) [0x00097] in <f9d5c992783f4cb69a111f6b34a7123f>:0

**Comment by FilipeSilvens** [comment]
@stevemk14ebr can you replace the LoadLibrary function in NativeMethods.Unix.cs with the one I posted above to see if the error is the same on different ubuntu versions?

Also don't forget to import dlerror above
```c#
[DllImport("libdl.so")]
private static extern IntPtr dlerror();
```

**Comment by stevemk14ebr** [comment]
yup it is: 

> Unhandled Exception:
System.Exception: dlopen exception: /home/steve/Desktop/ReClass.NET/ReClass.NET/bin/Debug/x86/NativeCore.so: undefined symbol: _ZNKSt25__codecvt_utf8_utf16_baseIDsE6do_outER11__mbstate_tPKDsS4_RS4_PcS6_RS6_
  at ReClassNET.Native.NativeMethodsUnix.LoadLibrary (System.String fileName) [0x00035] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Native.NativeMethods.LoadLibrary (System.String name) [0x00001] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Core.InternalCoreFunctions.Create () [0x00021] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Core.CoreFunctionsManager..ctor () [0x00013] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Program.Main (System.String[] args) [0x00097] in <a4bd8c0950014f688e171852a200e591>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: dlopen exception: /home/steve/Desktop/ReClass.NET/ReClass.NET/bin/Debug/x86/NativeCore.so: undefined symbol: _ZNKSt25__codecvt_utf8_utf16_baseIDsE6do_outER11__mbstate_tPKDsS4_RS4_PcS6_RS6_
  at ReClassNET.Native.NativeMethodsUnix.LoadLibrary (System.String fileName) [0x00035] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Native.NativeMethods.LoadLibrary (System.String name) [0x00001] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Core.InternalCoreFunctions.Create () [0x00021] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Core.CoreFunctionsManager..ctor () [0x00013] in <a4bd8c0950014f688e171852a200e591>:0 
  at ReClassNET.Program.Main (System.String[] args) [0x00097] in <a4bd8c0950014f688e171852a200e591>:0

**Comment by stevemk14ebr** [comment]
the offending symbol is: std::__codecvt_utf8_utf16_base<char16_t>::do_out(__mbstate_t&, char16_t const*, char16_t const*, char16_t const*&, char*, char*, char*&) const

but there's alot of undefined symbols, something is wrong in linking i think:

> nm NativeCore.so | grep ZNKSt25__codecvt_utf8_utf16_baseIDsE6do_outER11__mbstate_tPKDsS4_RS4_PcS6_RS6 -B 3 -A 3

> nm --demangle NativeCore.so | grep 22518 -B 3 -A 3

**Comment by stevemk14ebr** [comment]
https://github.com/ReClassNET/ReClass.NET/pull/84 will catch these at link time, still don't know why there's so many undefined though.

**Comment by FilipeSilvens** [comment]
I have managed to fix the undefined symbols, but now I get an out of range exception when I start the program.
https://gist.github.com/FilipeSilvens/69194e690b5a2def90a34b58e085cfdb

The original issue which is also present in #47 can be fixed by linking `-lstdc++` and `-ldl` in the NativeCore's Makefile.

**Comment by stevemk14ebr** [comment]
Fixed in #86 and #85 may be incomplete fix for scroll bar behavior

**Comment by FilipeSilvens** [comment]
Yup, all works good now. Thank you for helping :D

**Comment by KN4CK3R** [comment]
Thank you @stevemk14ebr for your help!

**Comment by stevemk14ebr** [comment]
Welcome :tada:
