### ISSUE TITLE
Not building under Visual Studio 2017

### ISSUE THREAD

**Issue by MockbaTheBorg** [ReClassNET/ReClass.NET#92]
Hi there,

I apologize in advance if this has already been answered before, or if it is just a stupid question.
I have tried to build from source, but VS2017 complains about SQLite.
How do I install this dependency? I think this is all that's missing.

Thanks,
Mockba the Borg,

**Comment by KN4CK3R** [comment]
SQLite comes over Nuget. Rightclick on the solution and restore the Nuget packages. https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore
After the next release I will drop the support for the ReClass 2007 files to remove Sqlite then.

**Comment by MockbaTheBorg** [comment]
Awesome!

Thanks a lot.
