### ISSUE TITLE
Classes list not showing up after loading

### ISSUE THREAD

**Issue by dudztroyer** [ReClassNET/ReClass.NET#93]
Like the title says, the left panel classes are not showing when I load my rcnet class file (used with a older compiled version from mid 2018).

![devenv_2019-03-07_15-40-04](https://user-images.githubusercontent.com/26704955/53980600-6f4a1c00-40ef-11e9-8cd5-a681d4341697.png)

**Comment by KN4CK3R** [comment]
Thanks for the report. I noticed this today because "Clear Project" wasn't working anymore.

**Comment by dudztroyer** [comment]
Thanks! I already downloaded three samples within last month and all of those had this problems... Was starting to think that it was my env problem hehe

Keep up the good work
